# Dependencies
exclude: [vendor]
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Payam Nikdel
tagline:             'A Software Engineer Who Loves His Job.'
#description:         There are only 10 types of people in the world. Those who undertand binary and those who don't, and those who count from zero.
description:
url:                 http://payamn.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Payam Nikdel
  url:               http://nikdel.tk
  email:             pnikdel@gmail.com
  twitter: 	     PayamNikdel
  facebook:          pnikdel
  googleplus:           Payamnikdel
  github:            payamn
  linkedin:          pnikdel

# Custom vars
version:             1.0.0



collections:
  projects:
    output: true
